spring.application.name=portalingresso

spring.datasource.url=jdbc:postgresql://portal-ingresso-db.c2vu8cuq66zg.us-east-1.rds.amazonaws.com/postgres
spring.datasource.username=postgres
spring.datasource.password=anderson123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/event-realm

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=catalog-group

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.ticket_service.*

spring.kafka.consumer.properties.spring.json.value.default.type=com.portalingresso.dto.TicketOrderDTO

spring.kafka.consumer.properties.spring.json.use.type.headers=false

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true